# Generated by Django 5.0.2 on 2024-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='tipoToken',
            field=models.CharField(blank=True, default='EMAIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
