# Generated by Django 5.0.2 on 2024-08-22 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_token_status_alter_token_tipotoken_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stylelearning', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
