# Generated by Django 5.0.2 on 2024-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstyles',
            name='actividades',
            field=models.TextField(null=True),
        ),
    ]
